### ISSUE TITLE
polling is not working

### ISSUE THREAD

**Issue by firaskhf** [rsg98/homebridge-gpio-wpi2#25]
Hi
first thank you for the amazing work that you're putting on this plugin.
I have an issue that i hope you can help me with.
I have i PIR sensor that's connected on gpio6 pin 25, the problem is that i can't see the status of the pir unless i close and reopen the home app or swipe up on my iphone. as if the polling is not working, and i was unable to invert the status of it. Any suggestions?
this is how i'm configuring it
{
                "name" : "GPIO6",
                "pin"  : 25,
                "enabled" : "true",
                "mode" : "in",
                "pull" : "down",
                "inverted" : "false",
                "duration" : 0,
                "polling" : "true"
a request: I was wondering if u can add PIR Sensor or motion Sensor to the Type.
Regards.

**Comment by rsg98** [comment]
Can you try it with "polling": "false"?

It should trap events for input pins, so the more clunky polling mechanism
isn't required.

Can you confirm the version of the module, homebridge and wiringpi package
that you've got installed?

**Comment by firaskhf** [comment]
ok so i managed to fix the polling issue by making a clean install. now with poll on or off the response back to the home app in fixed. but still unable to invert the status of the PIR. with no motion the sensor shows OPEN, while with motion it shows closed. i want it the other way. any suggestions?
note that override cache and autoexport is true

**Comment by rsg98** [comment]
Do you have overrideCache set to true? (Example in the ReadMe) - homebridge caches the values you set, so if the first time you tried it, you hadn't set inverted to true, it might be ignoring your change.

**Comment by firaskhf** [comment]
yes overrideCache is set to true. you mean i need to set it as False?

**Comment by rsg98** [comment]
No, you have it set correctly, so I guess it's not that. In one of the
closed issues I described how to clear the cache manually - 

https://github.com/rsg98/homebridge-gpio-wpi2/tree/hardware-pwm-support#i-get-duplicate-pins-after-i-rename-them-or-the-plugin-is-ignoring-my-settings

**Comment by firaskhf** [comment]
i deleted everything in cachedAccessories file and restarted homebridge, still the same.

**Comment by rsg98** [comment]
Just to double check - you need to stop homebridge, delete, then start
(otherwise it cleverly replaces the cache!)

What type of PIR do you have and how are you wiring it up to the Pi?

**Comment by firaskhf** [comment]
this what i did actually. regarding the pir it's the HC-SR501 PIR MOTION DETECTOR
Data sheet: https://www.mpja.com/download/31227sc.pdf

**Comment by rsg98** [comment]
Sorry - got my head back in the right place now!

I think this was fixed by @jdtsmith in a1550b666aad4b1ded84ded6bdcbc8d93e83b79d - but I haven't yet published an updated module to npm (because I thought I'd have finished the other upgrades by now, but not much free time at the moment!)

If you can find ``GPIOAccessory.js`` under node_modules / homebridge-gpio-wpi2, try removing the line:

``sysfs.activeLow = (!self.inverted * 1);``

The fix that @jdtsmith supplied (#22) provides a good explanation of what's going on with my broken logic...

**Comment by firaskhf** [comment]
ok so i added the 2 slashes to the line to deactivate it //sysfs.activeLow = (!self.inverted * 1);
then made sure homebridge is stopped, deleted everything in cachedAccessories file, made sure overrideCache set to true, and of course "inverted" : "true", . unfortunately it's still the same. showing Open (contact sensor) by default, and when it detects movement it changes to closed. could it be because it's type is Contact Sensor?
regards

**Comment by rsg98** [comment]
It should be ok as a contact sensor. Does setting the inverted option in
the configure file have any effect?

**Comment by firaskhf** [comment]
So i figured out what was the problem regarding the invert state of the PIR. before it was showing as OPEN in the home app. what i wanted was to invert that state. i tried changing inverted state and pull state in the config.json file but with no luck.
**what i realized is that whenever you want to change a state in the config.json file, you need to clear the cachedAccessories file before starting homebridge.** even if "overrideCache" is set to true.

What i tried and worked for me was as follows:
stopped homebridge, then cleared the cachedAccessories file, then i changed the state of "inverted" from false to true, finally i restarted homebridge again.  voilà it worked :)

Hope sharing this will help anybody.
